# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'app-slack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app-slack
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'

end
